# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1

description: |
  This orb integrates open source licensing compliance and vulnerability checks into your CI/CD workflow.
  Docs - https://github.com/fossas/fossa-cli/blob/master/docs/user-guide.md/#cli-reference
display:
  home_url: https://fossa.com/
  source_url: https://github.com/fossas/fossa-cli-orb

examples:
  analyze_job:
    description: |
      Analyze a project from within your workflow automatically.
    usage:
      version: 2.1
      orbs:
        fossa-cli: fossa/cli@0.0.3
      workflows:
        fossa-integration:
          jobs:
            - fossa-cli/analyze:
                post-steps:
                  - run: # run more commands if desired

  custom_commands:
    description: Install and configure the Fossa CLI in your custom jobs.
    usage:
      version: 2.1
      orbs:
        fossa-cli: fossa/cli@0.0.3
      jobs:
        my-job:
          executor: fossa-cli/default # or your own custom executor
          steps:
            - checkout
            - fossa-cli/setup
            - run: echo "Run more commands here"

executors:
  default:
    description: |
      A basic linux environment. Override with your own Docker image if needed.
    docker:
    - image: <<parameters.image>>
    parameters:
      image:
        default: cimg/base@2019.08-node
        description: |
          Select a custom Docker image. https://hub.docker.com/r/circleci/
        type: string

jobs:
  analyze:
    description: |
      Analyze a project
    executor: default
    parameters:
      fossa-api-key:
        type: env_var_name
        default: FOSSA_API_KEY
        description: |
          The fossa-cli will check for the existence of a FOSSA_API_KEY environment variable.
          Users will need to obtain a FOSSA_API_KEY prior to running a FOSSA analysis.
          Please refer to https://docs.fossa.com/docs/api-reference for more details.
      save_artifact:
        type: boolean
        default: true
        description: Saves an artifact with the results of the analysis.
      debug:
        type: boolean
        default: false
        description: Include the boolean flag.
    steps:
      - checkout
      - setup
      - run:
          name: Fossa Analyze
          command: |
            mkdir -p /tmp/fossa/analyze
            FOSSA_API_KEY=<<parameters.fossa-api-key>> fossa analyze <<# parameters.debug >>--debug <</ parameters.debug >><<# parameters.save_artifact >>-o /tmp/fossa/analyze/fossa_results.txt<</ parameters.save_artifact >>
      - when:
          condition: << parameters.save_artifact >>
          steps:
            - store_artifacts:
                path: /tmp/fossa/analyze

commands:
  setup:
    description: |
      Executes all the commands necessary to integrate fossa-cli into your CI/CD workflow.
      Note that the fossa-cli will check for the existence of a FOSSA_API_KEY environment variable.
      Please refer to https://docs.fossa.com/docs/api-reference for more details regarding the
      FOSSA_API_KEY.
    steps:
      - run:
          name: Imports fossa-cli
          command: |
            curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - run:
          name: Initialize fossa-cli by generating a .fossa.yml configuration file
          command: fossa init
      - run:
          name: Analyze the project with fossa-cli and generate a dependency graph
          command: fossa analyze
