# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1

description: |
  This orb integrates open source licensing compliance and vulnerability checks into your CI/CD workflow.
  Source: https://github.com/fossas/fossa-cli-orb

examples:
  standard_fossa_usage:
    description: |
      If you have a standard CircleCI configuration file, you can simply add this
      orb and then run fossa-cli/setup to streamline open source compliance.
    usage:
      version: 2.1

      orbs:
        fossa-cli: fossa/cli@dev:alpha

      workflows:
        fossa-integration:
          commands:
            fossa-cli/setup

  custom_fossa_usage:
    description: |
      You can run any custom fossa-cli command that you wish. In the example
      below we are running `fossa analyze` with the debug flag enabled.
    usage:
      version: 2.1

      orbs:
        fossa-cli: fossa/cli@dev:alpha

      workflows:
        fossa-integration:
          commands:
            - fossa-cli/custom:
                custom-command: |
                  fossa analyze --debug

commands:
  setup:
    description: |
      Executes all the commands necessary to integrate fossa-cli into your CI/CD workflow.
    steps:
      - run:
          name: Imports fossa-cli
          command: |
            curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - run:
          name: Initialize fossa-cli by generating a .fossa.yml configuration file
          command: fossa init
      - run:
          name: Analyze the project with fossa-cli and generate a dependency graph
          command: fossa analyze
  custom:
    description: |
      Run any custom fossa-cli command (more instructions here: https://github.com/fossas/fossa-cli/blob/master/docs/user-guide.md/#cli-reference)
    parameters:
      custom-command:
        description: |
          Define any custom fossa-cli command.
        type: string
    steps:
      - run:
          name: Run any custom fossa=cli command.
          command: << parameters.command >>
